---
- hosts: all
- roles:
    - rhel-system-roles.network
  vars:
    network_connections:
      - name: ens192
        type: ethernet
        ip:
          gateway4: 192.168.10.1
          dns:
            - 192.168.10.11
            - 192.168.10.5
          dns_search:
            - srv.thelaw.idm
            - thelaw.idm
            - localdomain
          dns_options:
            - rotate
            - timeout:1
          ipv6_disabled: true
          dhcp4: no
          address:
            - 192.168.10.101/24